services:
  - type: web
    name: daily-plan-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MYSQLHOST
        sync: false
      - key: MYSQLUSER
        sync: false
      - key: MYSQLPASSWORD
        sync: false
      - key: MYSQLDATABASE
        sync: false
      - key: MYSQLPORT
        sync: false
    plan: free
